### ISSUE TITLE
Atom live server is not working

### ISSUE THREAD

**Issue by mkckkcm** [jas-chen/atom-live-server#57]
I am on Mac runnning SIerra 10.12.4. I downloaded the latest version of ATOM today (1.17.0) and have installed the latest version of Atom Live Server (2.1.2). However, under the Packages menu there is no option for this. Also, trying and of the keyboard shortcuts does nothing either. Any suggestions on why it is not working?

**Comment by M33x0** [comment]
Hi ,i hope you are doing good.I have some issue too with this packages.Things was working good,but today i have thoses message

![selection_011](https://cloud.githubusercontent.com/assets/16633738/26260612/bac35122-3cc5-11e7-8747-7ac8f8f1f27b.png)
![selection_012](https://cloud.githubusercontent.com/assets/16633738/26260619/c1ad4718-3cc5-11e7-845e-1e156ed198da.png)

**Comment by mkckkcm** [comment]
Hi

Thanks for the reply.  By any chance, does this package require any particular software to work? Some application I need on my mac that maybe I don't have? Node.js perhaps?

Thanks.

**Comment by danielnieto** [comment]
This is because the package is incompatible with the new version of Atom, you can rebuild the packages for this latest version quite easily, follow these steps:

1. Restart Atom
2. Bring up the command palette (cmd + shift + p) and type "incompatible packages: view"
3. That screen will list all the packages that need to be rebuilt, just click on the "Rebuild" button 
4. Atom will ask you to restart it, do so, and that's it, Atom Live Server is now working

**Comment by mkckkcm** [comment]
Thank you!

Melissa

**Comment by Tony-Thomas** [comment]
Well done, @danielnieto !!

**Comment by jas-chen** [comment]
Thank @danielnieto for the solution!

**Comment by mkckkcm** [comment]
Thank you @danielnieto! That solved the issue. I am very grateful for your help!

**Comment by Kingwindie** [comment]
what happens when atom-live-server is not showing on the incompatible packages list?The list is empty, and atom-live-server is still not working, it says atom live server has stopped  when I click on it, and then disappears in the packages list

**Comment by jas-chen** [comment]
@Kingwindie plz open a new issue, thanks
